version: "3.8"

services:
  db:
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_USER=user32
      - POSTGRES_DB=database-32
    image: postgres:latest
    networks:
      - backend
      
  app:
    container_name: app
    image: poviraevsergei/market:v2
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
    depends_on:
      - db
    networks:
      - backend
    volumes:
      - app_data:/c32/logs
      
networks:
  backend:
    driver: bridge
  
volumes:
  app_data: